### ISSUE TITLE
Doesnt work as documentation explains

### ISSUE THREAD

**Issue by dmtzs** [GitHub30/win11toast#27]
I have the next script:
```python
from win11toast import toast


toast(title="Some title", body="Some body", icon="bell.ico", duration="short")
```

I dont get any error but just stat in a loop without doing nothing

Thank you in advance

**Comment by MadobyPy** [comment]
I think the issue lies with the icon's path,
try adding the full path of your icon instead of the relative path:

Example:
```
# Don't forget to change this path
#you can store the path in a variable
icon_path = r"D:\PythonApp\App-1-name\Assets\bell.ico"`
toast(title="Some title", body="Some body", icon=icon_path, duration="short")

# OR Add it directly
toast(title="Some title", body="Some body", icon=r"D:\PythonApp\App-1-name\Assets\bell.ico", duration="short")
```

(r --> Raw), don't forget adding (r) before the string, it indicates that the \ (slashes) are treated as literal characters and not as escape characters
alternatively: you can use double slashes in your path without (r), as follows:

(add your path)
```
icon_path = "D:\\PythonApps\\App-1-name\\Assets\\bell.ico"
toast(title="Some title", body="Some body", icon=icon_path, duration="short")

# OR
toast(title="Some title", body="Some body", icon="D:\\PythonApps\\App-1-name\\Assets\\bell.ico", duration="short")
```

I hope adding the full path solves the issue
Good luck

**Comment by dmtzs** [comment]
Will try, I will be back if this works just to let you know.
Thank you

**Comment by dmtzs** [comment]
It works in that way, I think then the only problem is to enhance the errors cause if you run the original script I posted in this issue then you don't see any traceback until you press Ctrl + c, the code should exit by himself if its the case, but well.
Also thank you @MadobyPy , that solves the issue i had.
